---
name: Easy Env Vars
description: Set one or more persistent env vars, which can use full bash syntax and reference previous vars.
branding:
  icon: terminal
  color: gray-dark
inputs:
  env:
      description: Multi-line string ENV_NAME=VALUE
      required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: ${{ github.action_path }}/ezenv.sh <<<'${{ inputs.env }}'
